POST http://localhost:3000/videos
Content-Type: application/json

{
  "title": "Video ",
  "description": "Video ",
  "duration": 180
}

###

GET http://localhost:3000/videos?search=

###

PUT http://localhost:3000/videos/e68f8d3d-b0af-4a4f-9760-1d811dd21b7a
Content-Type: application/json

{
  "title": "Video node",
  "description": "NodeJS2",
  "duration": 180
}

###

DELETE http://localhost:3000/videos/6fe1ab42-3b75-4937-a522-faf92036f5a4
Content-Type: application/json

{
  "title": "Video 02",
  "description": "NodeJS2",
  "duration": 180
}
